// libotp module list.
[('CFNoQuitButton', 256), ('CFPageButton', 16), ('preloadCache', 
<built-in function preloadCache>), 
('WhisperPopup', <type 'libotp.WhisperPopup'>), 
('MarginPopup', <type 'libotp.MarginPopup'>), (
'NametagFloat3d', <type 'libotp.NametagFloat3d'>), 
('CFQuitButton', 32), 
('CImpulse', <type 'libotp.CImpulse'>), 
('Dtool_AddToDictionary', <built-in function Dtool_AddToDictionary>), 
('ChatBalloon', <type 'libotp.ChatBalloon'>), 
('PathTable', <type 'libotp.PathTable'>), 
('NametagFloat2d', <type 'libotp.NametagFloat2d'>), 
('Nametag', <type 'libotp.Nametag'>), 
('Dtool_BorrowThisReference', <built-in function Dtool_BorrowThisReference>), 
('Dtool_PyNativeInterface', 1), ('NametagGroup', <type 'libotp.NametagGroup'>), 
('Nametag3d', <type 'libotp.Nametag3d'>), ('__doc__', None), ('CFThought', 2), ('CFTimeout', 8), 
('__file__', 'C:\\Users\\Nicholas\\Desktop\\Nicholas\\Computer\\Desktop\\Nicholas\\Computer\\ToontownOnline\\libotp.dll'), 
('MarginManager', <type 'libotp.MarginManager'>), ('NametagGlobals', <type 'libotp.NametagGlobals'>), 
('__name__', 'libotp'), ('CFQuicktalker', 4), ('CMover', <type 'libotp.CMover'>), 
('CMoverGroup', <type 'libotp.CMoverGroup'>), ('prepareAvatar', <built-in function prepareAvatar>), 
('printError', <built-in function printError>), ('listProcessModules', <built-in function listProcessModules>), 
('CFSndOpenchat', 128), ('CFReversed', 64), ('Nametag2d', <type 'libotp.Nametag2d'>), 
('ClickablePopup', <type 'libotp.ClickablePopup'>), ('CFSpeech', 1), 
('Settings', <type 'libotp.Settings'>)]